package br.contmatic.type;

public enum RamoAtividadeType {
	
	ABATEDOUROS_MATADOUROS("Abatedouros / Matadouros"),
	ADVOCACIA("Advocacia"),
	AGRICULTURA("Agricultura"),
	ALIMENTOS_E_BEBIDAS("Alimentos e Bebidas"),
	ANIMAIS("Animais"),
	ARTE("Arte"),
	ARTE_E_ANTIGUIDADES("Arte e Antiguidades"),
	ARTIGOS_RELIGIOSOS("Artigos Religiosos"),
	ASSINATURAS_E_REVISTAS("Assinaturas e Revistas"),
	AUTOMOVEIS_E_VEICULOS("Autoóveis e Veículos"),
	BEBES_E_CIA("Bebês & Cia"),
	BLU_RAY("Blu-ray"),
	BRINDES_E_MATERIAIS_PROMOCIONAIS("Brindes e Materiais Promocionais"),
	BRINQUEDOS_E_GAMES("Brinquedos e Games"),
	CARTORIOS("Cartórios"),
	CASA_E_DECORACAO("Casa e Decoração"),
	CASA_LOTERICA("Casas de Lotéricas"),
	CDS("CDs"),
	CINEMAS("Cinemas"),
	COLECIONAVEIS("Colecionáveis"),
	COMPRAS_COLETIVAS("Compras Coletivas"),
	COMUNICACOES("Comunicações"),
	CONSTRUCOES("Construções"),
	CONSTRUCAO_E_FERRAMENTAS("Construção e Ferramentas"),
	CONSORCIOS("Consórcios"),
	CONVENIENCIA("Lojas de Conveniências"),
	COSMETICOS_E_PERFUMARIA("Cosméticos e Perfumaria"),
	CURSOS_E_EDUCACAO("Cursos e Educação"),
	DECORACOES("Decorações"),
	DISCOS_DE_VINIL("Díscos de Vinil"),
	DVDS("DVDs"),
	ELETRODOMESTICOS("Eletrodomésticos"),
	ELETRONICOS("Eletrônicos"),
	EMISSORAS_DE_RADIO("Emissoras de Rádio"),
	EMISSORAS_DE_TELEVISAO("Emissoras de Televisão"),
	EMPREGOS("Empregos"),
	EMPRESAS_DE_MARKETING("Empresas de Marketing"),
	ENGENHARIA("Engenharia"),
	ESCOTERICOS_MISTICOS("Escoteiros Misticos"),
	ESPORTE_E_LAZER("Esporte e lazer"),
	ESTACIONAMENTO("Estacionamentos"),
	EXPORTACAO_IMPORTACAO("Exportação e Importação"),
	FESTAS_EVENTOS("Festas / Eventos"),
	FITAS_K7_E_GRAVADAS("Fitas K7 e Gravadas"),
	FLORES_CESTAS_E_PRESENTES("Flores, Cestas e Presentes"),
	FOTOGRAFIA("Fotografia"),
	FINANCEIRO("Financeiro"),
	FUNERARIO("Funeraria"),
	GEOLOGIA("Geologia"),
	GERAL("Serviços Gerais"),
	GRAFICA("Gráfica"),
	HD_DVD("Hd DVD"),
	HARDWARE("Hardware"),
	RELIGIOSO("Religioso"),
	INDUSTRIA_COMERCIOS_E_NEGOCIOS("Indústria de Comércios e Negócios"),
	INFLAVEIS_PROMOCIONAIS("Infláveis Promocionais"),
	INFORMATICA("Informática"),
	INTERNET("Internet"),
	INSTRUMENTOS_MUSICAIS("Instrumentos Músicais"),
	JOALHERIA("Joalheria"),
	JORNAIS_REVISTAS("Jornais e Revistas"),
	LAZER("Lazer"),
	LEILOES("Leilões"),
	LIVROS("Livros"),
	LIMPEZA("Limpeza"),
	MAO_DE_OBRA("Mão de Obra"),
	MEIO_AMBIENTE("Meio Ambiente"),
	MODA_E_VISUAL("Moda e Visual"),
	MOTEIS("Moteis"),
	MUSICA_DIGITAL("Música Digital"),
	NEGOCIOS_E_OPORTUNIDADES("Negócios e Oportunidades"),
	ORGAO_PUBLICO("Órgão Publico"),
	OUTROS_SERVICOS("Outros Serviços"),
	OUTROS_SERVICOS_DE_AVALIACAO("Outros Serviços de Avaliação"),
	PAPELARIA_E_ESCRITORIO("Papelaria e Escritório"),
	PASCOA("Páscoa"),
	PESQUISAS("Pesquisas"),
	PET_SHOP("Pet Shop"),
	SAUDE("Saúde"),
	SEGURADORAS("Seguradoras"),
	SEGURANCA("Segurança"),
	SERVICOS_AEROPORTOS("Serviçoes de Aeroportos"),
	SERVICOS_ALUGUEIS_LOCACAO("Serviçoes de Alugueis e Locação"),
	SERVICOS_ARMAZENAGENS("Serviços de Armazenagens"),
	SERVICOS_ACESSORIAS("Serviços de Acessorias"),
	SERVICOS_ASSISTENCIA_TECNICA_INSTALACOES("Serviços de Assistência Técnica e Instalações"), 
	SERVICOS_BANCOS_DE_SANGUE("Serviços de Banco de Sangue"),
	SERVICOS_SOCIAIS("Serviços Sociais"),
	SINALIZACAO("Serviços de Sinalização"),
	SINDICATOS("Sindicatos"),
	SOM("Instalaçoes e Manutençoes de Equipamentos de Som"),
	SOFTWARE("Desenvolvimento de Software"),
	SEX_SHOP("Sex Shop"),
	SHOPPING("Shopping Centers"),
	TABACARIA("Tabacarias"),
	TARIFAS_BANCARIAS("Tarifas Bancarias"),
	TARIFAS_TELEFONICAS("Tafiras Telefonicas"),
	TELEFONIA("Telefonia"),
	TRADUCOES("Traduções"),
	TRASPORTE("Transporte"),
	TURISMO("Turismo"),
	UNIDADE_PUBLICA("Unidade Pública"),
	VEICULOS("Veículos"),
	VETERINARIA("Veterinária");
	
	private String descricao;

	private RamoAtividadeType(String descricao) {
		this.descricao = descricao;
	}

	public String getDescricao() {
		return descricao;
	}
	
}
